// Массив книг, используемый на главной и в каталоге
const books = [
    { title: "Отцы и дети", author: "И.С. Тургенев", year: "1862", genre: "Роман", pages: "288", language: "Русский", description: "Роман о конфликте между либералами и нигилистами в России 1860-х годов.", link: "#", downloadLink: "https://royallib.com/get/fb2/turgenev_ivan/ottsi_i_deti.zip" },
    { title: "Преступление и наказание", author: "Ф.М. Достоевский", year: "1866", genre: "Роман", pages: "671", language: "Русский", description: "Психологический роман о преступлении и его последствиях. История Раскольникова.", link: "#", downloadLink: "https://royallib.com/get/fb2/dostoevskiy_fedor/prestuplenie_i_nakazanie.zip" },
    { title: "Война и мир", author: "Л.Н. Толстой", year: "1869", genre: "Роман-эпопея", pages: "1225", language: "Русский", description: "Роман-эпопея о судьбах дворянских семей на фоне войны 1812 года.", link: "#", downloadLink: "https://tolstoy.ru/upload/iblock/b52/voina-i-mir.fb2" },
    { title: "Очарованный странник", author: "Н.С. Лесков", year: "1873", genre: "Повесть", pages: "224", language: "Русский", description: "Повесть о жизни Ивана Флягина, человека с необычной судьбой.", link: "#", downloadLink: "https://royallib.com/get/fb2/leskov_Hikolay/ocharovanniy_strannik.zip" },
    { title: "Вишневый сад", author: "А.П. Чехов", year: "1904", genre: "Комедия", pages: "96", language: "Русский", description: "Пьеса о судьбе дворянской усадьбы и её обитателей.", link: "#", downloadLink: "https://royallib.com/get/fb2/chehov_anton/vishneviy_sad.zip" },
    { title: "Иуда Искариот", author: "Л.Н. Андреев", year: "1907", genre: "Повесть", pages: "128", language: "Русский", description: "Психологическая повесть, переосмысливающая библейский сюжет о предательстве Иуды.", link: "#", downloadLink: "https://royallib.com/get/fb2/andreev_leonid/iuda_iskariot.zip", filename: "Андреев - Иуда Искариот" },
    { title: "На дне", author: "М. Горький", year: "1902", genre: "Пьеса", pages: "160", language: "Русский", description: "Драма о жизни обитателей ночлежки, их надеждах и разочарованиях.", link: "#", downloadLink: "http://az.lib.ru/g/gorxkij_m/gorxkij_m-text_0180.fb2.zip", filename: "Горький - На дне" },
    { title: "Тихий Дон", author: "М.А. Шолохов", year: "1940", genre: "Роман-эпопея", pages: "1504", language: "Русский", description: "Роман-эпопея о жизни донского казачества в период Первой мировой войны, революции и Гражданской войны.", link: "#", downloadLink: "#" },
    { title: "Молодая гвардия", author: "А.А. Фадеев", year: "1946", genre: "Роман", pages: "672", language: "Русский", description: "Роман о деятельности подпольной комсомольской организации 'Молодая гвардия' в оккупированном Краснодоне.", link: "#", downloadLink: "https://www.litres.ru/gettrial/?art=139742&format=fb2.zip&lfrom=1116205709", filename: "Фадеев - Молодая гвардия" },
    { title: "Один день Ивана Денисовича", author: "А.И. Солженицын", year: "1962", genre: "Повесть", pages: "176", language: "Русский", description: "Повесть о жизни заключенного в сталинском лагере. Один день из жизни Ивана Денисовича Шухова.", link: "#", downloadLink: "https://download.librebook.me/download/13/61/57/272560_440.fb2", filename: "Солженицын - Один день Ивана Денисовича" },
    { title: "Прощание с Матерой", author: "В.Г. Распутин", year: "1976", genre: "Повесть", pages: "256", language: "Русский", description: "Повесть о затоплении острова Матера при строительстве ГЭС. О конфликте между прогрессом и традиционным укладом жизни.", link: "#", downloadLink: "https://fantasy-worlds.ru/trial/txt/70647691.fb2.zip" },
    { title: "Иркутская история", author: "А.Н. Арбузов", year: "1959", genre: "Пьеса", pages: "128", language: "Русский", description: "Драма о любви и предательстве, о выборе между личным счастьем и долгом.", link: "#", downloadLink: "https://download.librebook.me/download/07/12/00/198508_37.fb2", filename: "Арбузов - Иркутская история" },
    { title: "Старший сын", author: "А.В. Вампилов", year: "1968", genre: "Пьеса", pages: "96", language: "Русский", description: "Комедия о случайной встрече и неожиданных последствиях. Студент выдает себя за старшего сына в чужой семье.", link: "#", downloadLink: "https://royallib.com/get/fb2/vampilov_aleksandr/starshiy_sin.zip" },
    { title: "451 градус по Фаренгейту", author: "Р. Брэдбери", year: "1953", genre: "Роман", pages: "256", language: "Английский", description: "Антиутопический роман о будущем обществе, где книги запрещены и сжигаются.", link: "#", downloadLink: "https://royallib.com/get/fb2/Bradbury_Raymond/Fahrenhait_451.zip" },
    { title: "Старик и море", author: "Э. Хемингуэй", year: "1952", genre: "Повесть", pages: "128", language: "Русский", description: "Повесть о старом кубинском рыбаке Сантьяго и его борьбе с огромной рыбой.", link: "#", downloadLink: "https://royallib.com/get/fb2/heminguey_ernest/starik_i_more.zip" }
];

export default books; 